name: MacOS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  macos:
    name: MacOS Release (Universal)
    runs-on: macos-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: [ 'v0.7.1' ]

    env:
      OSX_BUILD_UNIVERSAL: 1
      GEN: ninja

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/fasql-deploy-role

      - name: Install Ninja
        run: brew install ninja zlib

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Checkout DuckDB to version
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

         # Build extension
      - name: Build extension
        shell: bash
        run: |
          make release
          make test

      - name: Deploy New Release
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET }}
        run: |
          ./scripts/extension-upload.sh fasql ${{ github.ref_name }} ${{ matrix.duckdb_version }} osx_amd64 $BUCKET_NAME true
          ./scripts/extension-upload.sh fasql ${{ github.ref_name }} ${{ matrix.duckdb_version }} osx_arm64 $BUCKET_NAME true
