name: Windows

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  windows:
    name: Release
    runs-on: windows-latest
    strategy:
      matrix:
        duckdb_version: [ 'v0.7.1' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/fasql-deploy-role

      - name: Checkout DuckDB to version
        # Add commits/tags to build against other DuckDB versions
        if: ${{ matrix.duckdb_version != 'v0.7.1' }}
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - name: Build extension
        shell:
          bash -l {0}
        run: |
          make release
          build/release/test/Release/unittest.exe

      - uses: actions/upload-artifact@v2
        with:
          name: linux-extensions-64-aarch64
          path: |
            build/release/extension/fasql/fasql.duckdb_extension

      - name: Deploy
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET }}
        shell:
          bash -l {0}
        run: |
          cd duckdb
          git fetch --tags
          export DUCKDB_VERSION=`git tag --points-at HEAD`
          export DUCKDB_VERSION=${DUCKDB_VERSION:=`git log -1 --format=%h`}
          cd ..
          if [[ "$AWS_ACCESS_KEY_ID" == "" ]] ; then
            echo 'No key set, skipping'
          elif [[ "$GITHUB_REF" =~ ^(refs/tags/v.+)$ ]] ; then
            ./scripts/extension-upload.sh fasql ${{ github.ref_name }} $DUCKDB_VERSION windows_amd64 $BUCKET_NAME true
          elif [[ "$GITHUB_REF" =~ ^(refs/heads/main)$ ]] ; then
            ./scripts/extension-upload.sh fasql `git log -1 --format=%h` $DUCKDB_VERSION windows_amd64 $BUCKET_NAME false
          fi
